logdest: c:\data\code\testfolder\logs
loglevel: INFO
transfers:
  - name: Result Files
    source_directory: c:\data\code\testfolder\tf1
    destination: /path/to/destination1
    delay: 1

  - name: Log Files
    source_directory: c:\data\code\testfolder\tf2
    destination: /path/to/destination2
    streaming: True