# Global settings

logfile: c:\logs\logfile.log
loglevel: info
service_heartbeat: true
transfers:
  - name: File Folder 1 
    source_directory: c:\path_to_folder
    transfertype: sftp
    username: tfuser
    privatekey: c:\path_to_folder\private_key.priv
    server: 192.168.214.128
    port: 22
    remotepath: incoming
    streaming: false
    overwrite_dest: false
    action_on_success: archive
    action_on_fail: archive
    archive_dest: c:\path_to_folder\archive
    fail_dest: c:\path_to_folder\fail
    filter: "\\.(txt|csv)$"

  - name: Log Files
    source_directory: c:\path_to_another_folder
    transfertype: sftp
    destination: /path/to/destination2
    username: tfuser
    privatekey: c:\path_to_another_folder\private_key.priv
    server: 192.168.214.128
    port: 22
    remotepath: incoming
    streaming: false
    filter: "\\.(jpg|png|gif)$"