
name: test-runs

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]


jobs:
  test:
    if: ${{ !contains(join(github.event.commits.*.modified, ' '), '.md') }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
